# 03. CatBoost: raw vs log target, default vs tuned

Four CatBoost models, one interface (fit_model(..., target_transform="none" | "log1p")):

| model | target | hyperparameters |
|---|---|---|
| catboost_raw (v1) | num_sold | default |
| catboost_log (v2) | log1p(num_sold) | default |
| catboost_raw_tuned (v3) | num_sold | best on validation |
| catboost_log_tuned (v3) | log1p(num_sold) | best on validation |

**Rules.** Hyperparameters and model choice use only the validation folds (2013-2015). The 2016 test
is scored once per final model after all choices are made, and its results are never fed back into tuning.
tune_catboost raises an error if it receives test-year rows.

> The full run (2 targets x 10 candidates x 3 folds + final fits) takes a while. Run all cells in order.

In [1]:
import sys
from pathlib import Path

current_dir = Path.cwd()
PROJECT_ROOT = next(
    (p for p in (current_dir, current_dir.parent) if (p / "src" / "validation.py").is_file()),
    None,
)
if PROJECT_ROOT is None:
    raise RuntimeError(f"Project root not found from: {current_dir}")
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from IPython.display import Markdown, display

RESULTS_DIR = PROJECT_ROOT / "results"
TRAIN_PATH = PROJECT_ROOT / "data" / "train.csv"

In [2]:
import catboost
from src.experiments import prepare_data, run_catboost_experiments, select_final_model, tuning_effect
from src.validation import (
    TEST_YEAR, VALIDATION_YEARS, assert_no_test_data, describe_scheme,
    expanding_window_splits, split_development_test,
)

print("Python:", sys.version.split()[0], "| pandas:", pd.__version__,
      "| numpy:", np.__version__, "| CatBoost:", catboost.__version__)
print(describe_scheme())

Python: 3.14.4 | pandas: 3.0.5 | numpy: 2.5.3 | CatBoost: 1.2.10
fold_1_2013: train 2010-2012 -> validate 2013
fold_2_2014: train 2010-2013 -> validate 2014
fold_3_2015: train 2010-2014 -> validate 2015
test_2016: train 2010-2015 -> test 2016 (independent, final evaluation only)

## 1. Data and split integrity checks

In [3]:
df = prepare_data(TRAIN_PATH)     # sorted, missing targets dropped, date features added
dev_df, test_df = split_development_test(df)

assert dev_df["date"].max() < test_df["date"].min()
assert_no_test_data(dev_df)
for train_part, val_part in expanding_window_splits(dev_df):
    assert train_part["date"].max() < val_part["date"].min()
    assert val_part["date"].max() < test_df["date"].min()      # validation never touches test

pd.DataFrame([
    {"split": f"val_{y}", "rows": int((dev_df["date"].dt.year == y).sum())} for y in VALIDATION_YEARS
] + [{"split": f"test_{TEST_YEAR}", "rows": len(test_df)}])

       split   rows
0   val_2013  31721
1   val_2014  31823
2   val_2015  31643
3  test_2016  31767

## 2. Train, tune on validation, evaluate on test

In [4]:
out = run_catboost_experiments(df, RESULTS_DIR)
metrics = out["metrics"]

catboost_raw fold_1_2013: MAPE = 15.8793%
catboost_raw fold_2_2014: MAPE = 15.9177%
catboost_raw fold_3_2015: MAPE = 23.7564%
[none] reference              mean validation MAPE = 18.5178
[none] shallower              mean validation MAPE = 26.9820
[none] deeper                 mean validation MAPE = 14.3259
[none] slow_lr_800            mean validation MAPE = 18.2445
[none] slow_lr_1000           mean validation MAPE = 17.7527
[none] fast_lr                mean validation MAPE = 18.5228
[none] more_regularization    mean validation MAPE = 18.8823
[none] medium_regularization  mean validation MAPE = 17.4064
[none] shallow_slow           mean validation MAPE = 26.1674
[none] deep_slow              mean validation MAPE = 14.4311
catboost_log fold_1_2013: MAPE = 6.5833%
catboost_log fold_2_2014: MAPE = 7.3343%
catboost_log fold_3_2015: MAPE = 13.5992%
[log1p] reference              mean validation MAPE = 9.1723
[log1p] shallower              mean validation MAPE = 9.7044
[log1p] deeper                 mean validation MAPE = 9.3893
[log1p] slow_lr_800            mean validation MAPE = 9.4313
[log1p] slow_lr_1000           mean validation MAPE = 9.3798
[log1p] fast_lr                mean validation MAPE = 9.2231
[log1p] more_regularization    mean validation MAPE = 9.3265
[log1p] medium_regularization  mean validation MAPE = 9.1889
[log1p] shallow_slow           mean validation MAPE = 9.6734
[log1p] deep_slow              mean validation MAPE = 9.1660
catboost_raw test_2016: MAPE = 15.0596%
catboost_log test_2016: MAPE = 6.5652%
catboost_raw_tuned test_2016: MAPE = 10.7624%
catboost_log_tuned test_2016: MAPE = 6.5670%

## 3. Validation results (per fold)

In [5]:
val = metrics[metrics["validation_scheme"] == "expanding_window"]
val.pivot_table(index="model", columns="fold", values="mape").assign(
    mean_validation=lambda d: d.mean(axis=1)
).round(4)

fold                fold_1_2013  fold_2_2014  fold_3_2015  mean_validation
model
catboost_log             6.5833       7.3343      13.5992           9.1723
catboost_log_tuned       6.7878       7.0914      13.6188           9.1660
catboost_raw            15.8793      15.9177      23.7564          18.5178
catboost_raw_tuned      12.1009      12.3407      18.5361          14.3259

## 4. Hyperparameter search (validation folds only)

In [6]:
pd.set_option("display.width", 200)
out["tuning"].round(4)

   target_transform                   name  iterations  depth  learning_rate  l2_leaf_reg  mape_fold_1_2013  mape_fold_2_2014  mape_fold_3_2015  mean_validation_mape
0              none                 deeper         500      8           0.05            3           12.1009           12.3407           18.5361               14.3259
1              none              deep_slow         800      8           0.03            5           12.3526           11.7790           19.1618               14.4311
2              none  medium_regularization         800      6           0.05            5           14.6583           14.6532           22.9076               17.4064
3              none           slow_lr_1000        1000      6           0.03            3           15.5742           15.0548           22.6292               17.7527
4              none            slow_lr_800         800      6           0.03            3           16.1957           14.9810           23.5568               18.2445
5              none              reference         500      6           0.05            3           15.8793           15.9177           23.7564               18.5178
6              none                fast_lr         500      6           0.10            3           17.8479           15.6442           22.0764               18.5228
7              none    more_regularization         500      6           0.05           10           16.9797           15.5982           24.0689               18.8823
8              none           shallow_slow        1000      4           0.03            5           24.1910           25.2059           29.1054               26.1674
9              none              shallower         500      4           0.05            3           24.4445           27.7446           28.7568               26.9820
10            log1p              deep_slow         800      8           0.03            5            6.7878            7.0914           13.6188                9.1660
11            log1p              reference         500      6           0.05            3            6.5833            7.3343           13.5992                9.1723
12            log1p  medium_regularization         800      6           0.05            5            6.7427            7.3814           13.4427                9.1889
13            log1p                fast_lr         500      6           0.10            3            6.6809            7.6585           13.3298                9.2231
14            log1p    more_regularization         500      6           0.05           10            6.8433            7.2607           13.8756                9.3265
15            log1p           slow_lr_1000        1000      6           0.03            3            6.7722            7.6824           13.6847                9.3798
16            log1p                 deeper         500      8           0.05            3            7.5546            7.0625           13.5508                9.3893
17            log1p            slow_lr_800         800      6           0.03            3            6.8543            7.7200           13.7196                9.4313
18            log1p           shallow_slow        1000      4           0.03            5            6.8830            8.0500           14.0871                9.6734
19            log1p              shallower         500      4           0.05            3            6.9664            8.0963           14.0504                9.7044

In [7]:
for name, info in out["chosen"].items():
    print(name, "->", info["candidate"], info["params"])

catboost_raw_tuned -> deeper {'iterations': 500, 'depth': 8, 'learning_rate': 0.05, 'l2_leaf_reg': 3.0}
catboost_log_tuned -> deep_slow {'iterations': 800, 'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 5.0}

## 5. Does tuning actually help?

In [8]:
effect = tuning_effect(pd.read_csv(RESULTS_DIR / "metrics.csv"))
effect.round(4)

  target_transform  validation_default  validation_tuned  validation_improvement_pp  test_default  test_tuned  test_improvement_pp
0             none             18.5178           14.3259                     4.1919       15.0596     10.7624               4.2971
1            log1p              9.1723            9.1660                     0.0063        6.5652      6.5670              -0.0019

*_improvement_pp is default - tuned in percentage points: positive means tuning helped.
If the validation and test improvements disagree (or are close to zero), tuning did not give a
reliable gain; state that in the report instead of claiming an improvement.

## 6. Independent test (2016) and comparison with baselines

In [9]:
all_metrics = pd.read_csv(RESULTS_DIR / "metrics.csv")
final = select_final_model(all_metrics)
print("Final CatBoost model chosen on VALIDATION MAPE:", final)

test = all_metrics[all_metrics["validation_scheme"] == "final_test"]
test[["model", "version", "fold", "mape"]].sort_values("mape").reset_index(drop=True).round(4)

Final CatBoost model chosen on VALIDATION MAPE: catboost_log_tuned

                      model version       fold     mape
0              catboost_log      v2  test_2016   6.5652
1        catboost_log_tuned      v3  test_2016   6.5670
2        catboost_raw_tuned      v3  test_2016  10.7624
3  seasonal_naive_last_year      v1  test_2016  12.6879
4              catboost_raw      v1  test_2016  15.0596
5              group_median      v1  test_2016  18.1635
6    ridge_calendar_one_hot      v1  test_2016  18.2208

In [10]:
comparison = (
    all_metrics.groupby(["model", "validation_scheme"])["mape"].mean().unstack("validation_scheme")
    .rename(columns={"expanding_window": "validation_mean", "final_test": "test_2016"})
    .sort_values("test_2016")
)
comparison.round(4)

validation_scheme         validation_mean  test_2016
model
catboost_log                       9.1723     6.5652
catboost_log_tuned                 9.1660     6.5670
catboost_raw_tuned                14.3259    10.7624
seasonal_naive_last_year          12.8886    12.6879
catboost_raw                      18.5178    15.0596
group_median                      14.3944    18.1635
ridge_calendar_one_hot            16.1048    18.2208

## 7. Conclusions

All values in this section are MAPE on the original num_sold scale. Model selection uses only the
mean validation MAPE; the 2016 test is an independent final estimate.

- The log target is the main improvement: catboost_log has 9.17% validation MAPE and 6.57% test MAPE,
  compared with 18.52% and 15.06% for catboost_raw.
- Tuning substantially improves the raw-target model (18.52% → 14.33% on validation; 15.06% → 10.76% on test).
- Tuning does not provide a meaningful improvement for the log-target model: validation changes from 9.172%
  to 9.166%, while test MAPE changes from 6.565% to 6.567%. catboost_log_tuned is selected by the
  validation rule, but this difference is practically negligible.
- On the independent test, the selected model has 6.57% MAPE versus 12.69% for
  seasonal_naive_last_year — an improvement of 6.12 percentage points on identical rows.

The defensible conclusion is that the log target, rather than hyperparameter tuning, accounts for the
strong CatBoost result.